language: ruby
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
